name: Test Report Module GitHub CI

on:
  # execute on every PR
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dependencies build space
        run: mkdir dependencies
        shell: bash

      - name: Install dependencies
        working-directory: dependencies
        run: |
          echo "Installing Dependencies..."
          sudo apt update
          sudo apt install \
            g++ \
            g++-10 \
            make \
            build-essential \
            cmake \
            libgtest-dev \
            qtbase5-dev \
            libqt5xmlpatterns5-dev \
            libxerces-c-dev \
            pkg-config
          echo "Dependencies installed."
        shell: bash

      - name: Build framework
        # Currently this is building without the XSD file. If we want to expose
        # the build artifact after, we might as well need to add the XSD file.
        run: |
          echo Building framework...
          cmake -G "Unix Makefiles" -B./build -S . \
            -DCMAKE_INSTALL_PREFIX="./build" \
            -DENABLE_FUNCTIONAL_TESTS=$TEST_ENABLED  -DXERCES_ROOT="/usr" \
            -DQt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5/" \
            -DQt5XmlPatterns_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5XmlPatterns/"
          cmake --build ./build --target install --config Release -j4
          cmake --install ./build
          echo Done.
        shell: bash

      - name: Run GithubCIReport
        run: ./build/bin/GithubCIReport examples/viewer_example/resources/Result.xqar
        shell: bash
